#!/bin/bash
# User specific environment and startup programs



export PATH=$PATH:$HOME/bin

# Nuclide
export PATH=$PATH:/opt/facebook/nuclide/0.270.81972311/nuclide/pkg/nuclide-server/nuclide-start-server
shopt -s checkwinsize

unset USERNAME
export FBANDROID_DIR=/Users/blappert/fbsource/fbandroid
alias quicklog_update=/Users/blappert/fbsource/fbandroid/scripts/quicklog/quicklog_update.sh
alias qlu=quicklog_update
#export NVM_DIR="$HOME/.nvm"
#. "/usr/local/opt/nvm/nvm.sh"

# added by setup_fb4a.sh
export ANDROID_SDK=/opt/android_sdk
export ANDROID_AVD_HOME=/Users/blappert/.android/avd
export ANDROID_NDK_REPOSITORY=/opt/android_ndk
export ANDROID_HOME=$ANDROID_SDK
export PATH=$PATH:$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools

# for buck
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home

# OPAM configuration
. /Users/blappert/.opam/opam-init/init.sh > /dev/null 2> /dev/null; true

alias dexdump=$ANDROID_SDK/build-tools/23.0.1/dexdump
export FBANDROID=/Users/blappert/fbsource/fbandroid

export FBANDROID_DIR=/Users/blappert/data/fbsource/fbandroid
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
